preprocessor:
  input: C:\MLOPS\Diabetes_Pred-DVC-\data\raw\diabetes.csv
  output: C:\MLOPS\Diabetes_Pred-DVC-\data\preprocessed\data.csv

trainer:
  random_state: 42
  max_depth: 5
  n_estimators: 100
  data: data/processed/data.csv
  model: models/model.pkl
